# This is the wordup config:
# - You can customize two things here: 
# - Your wordup specific config and the config of your WordPress installation
# Documentation: https://docs.wordup.dev

# A wordup project is either of type 'plugins', 'themes' or 'installation'
type: themes
 
# The internal project name 
projectName: Wordup Example Project

# The slug of your project. CAUTION: You have to reinstall your dev server, when you change the slug.
slug: wordup-example-project


# WordPress installation config 
wpInstall:
  title: Wordup Example Project
  language: en_US
  users:
    - name: admin
      password: 123456
      email: test@example.com
      role: administrator
  plugins: {}
  themes: {}


